apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: order-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: Sk7*1997
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3307/lugx_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: us-central1-docker.pkg.dev/samathi-lugxgaming/lugx-repo/order-service:prod
          name: order-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
